=== J817B477/assignment-1--databases--cs-365--fall-2024/xml/student.dtd
<!--
The root element: student-body

The root must contain one or more student elements but no PCDATA or CDATA
-->
<!ELEMENT student-body (student)+>

<!--
The student element must contain one of each advisor, personal-info, academic-standing,
and metriculation-status element types
-->
<!ELEMENT student (personal-info,student-id, advisor,  academic-standing, metriculation-status)>
<!ELEMENT advisor EMPTY>

<!--
The personal-info element must contain one of each  identifiers and contact element types
-->
<!ELEMENT personal-info         (identifiers, contact)>
<!ELEMENT identifiers           EMPTY>
<!ELEMENT contact               EMPTY>
<!ELEMENT academic-standing     EMPTY>
<!ELEMENT metriculation-status  EMPTY>

<!--
All EMPTY elements have at least one attribute to store data. This is to ensure that the
grammer insists that certain data be present for each and in many instances require a value
be assigned to it.
-->


<!--
"identifiers" element attributes:
* "preferred-name" attribute must have character data; IS NOT required for each element instance
* "first" attribute must have character data; IS required for each element instance
* "middle" attribute must have character data; IS NOT required for each element instance
* "last" attribute must have character data; IS required for each element instance
-->
<!ATTLIST identifiers
          preferred-name  CDATA
          first           CDATA #REQUIRED
          middle          CDATA
          last            CDATA #REQUIRED>

<!--
"contact" element attributes:
* "phone" attribute must have character data; IS required for each element instance
* "first" attribute must have character data; IS required for each element instance
-->
<!ATTLIST contact
          email CDATA #REQUIRED
          phone CDATA #REQUIRED>

<!--
the "name" attribute of the "advisor" element must have character data
the attribute is required for each "advisor" element
-->
<!ATTLIST student-id
          id CDATA #REQUIRED>

<!--
the "name" attribute of the "advisor" element must have character data
the attribute is required for each "advisor" element
-->
<!ATTLIST advisor
          name CDATA #REQUIRED>

<!--
"academic-standing" element attributes:
* "gpa" attribute must have character data; IS required for each element instance
* "major" attribute must have character data; IS required for each element instance
* "minor" attribute must have character data; IS required for each element instance
-->

<!ATTLIST academic-standing
          gpa   CDATA #REQUIRED
          major CDATA #REQUIRED
          minor CDATA #REQUIRED>

<!--
"contact" element attributes:
* "status" attribute value restricted to "full-time"or "part-time"; IS required for each element instance
* "year" attribute value restricted to four values; IS required for each element instance
* "start-date" attribute must have character data; IS required for each element instance
* "graduation-date" attribute must have character data; IS required for each element instance
-->
<!ATTLIST metriculation-status
          status          (full-time|part-time) #REQUIRED
          year            (first year|second year|third year|fourth year) #REQUIRED
          start-date      CDATA #REQUIRED
          graduation-date CDATA #REQUIRED>

=== J817B477/assignment-1--databases--cs-365--fall-2024/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="../xml/style.css"?>
<!DOCTYPE student SYSTEM "../xml/student.dtd" > <!--provides what attributes and nested elements each element of a given type can and cannot have up to the root element-->

<student-body>
  <student>
    <personal-info>
      <identifiers  preferred-name = "(Sting)"
                    first = "Gordon"
                    middle = "Matthew"
                    last = "Sumner"
      />
      <contact  email = "sting@thepolice.com"
                phone = "212.123.4567"
      />
    </personal-info>
    <student-id id = "1234567"/>
    <advisor name = "Andy Summers"/>
    <academic-standing  gpa = "4.0"
                        major = "Music"
                        minor = "English"
    />
    <metriculation-status status = "full-time"
                          year = "first year"
                          start-date = "08-25-1969"
                          graduation-date = "08-25-1969"
    />
  </student>

  <student>
    <personal-info>
      <identifiers  first = "Kim"
                    last = "Thayil"
      />
      <contact  email = "kim@soundgarden.com"
                phone = "206.123.4567"
      />
    </personal-info>
    <student-id id = "4567890"/>
    <advisor name = "Chris Cornell"/>
    <academic-standing  gpa = "3.0"
                        major = "Philosophy"
                        minor = "Music"
    />
    <metriculation-status status = "full-time"
                          year = "second year"
                          start-date = "08-25-1978"
                          graduation-date = "05-01-1982"
    />
  </student>

  <student>
    <personal-info>
      <identifiers  preferred-name = "(Slash)"
                    first = "Saul"
                    last = "Hudson"
      />
      <contact  email = "slash@gnr.com"
                phone = "213.456.8392"

      />
    </personal-info>
    <student-id id = "8302438"/>
    <advisor name = "Axl Rose"/>
    <academic-standing  gpa = "2.0"
                        major = "Music"
                        minor = "Criminal Justice"
    />
    <metriculation-status status = "part-time"
                          year = "fourth year"
                          start-date = "08-25-1983"
                          graduation-date = "05-01-1987"
    />
  </student>

  <student>
    <personal-info>
      <identifiers  first = "Emily"
                    last = "Kokal"
      />
      <contact  email = "emily@warpaint.com"
                phone = "213.123.7654"
      />
    </personal-info>
    <student-id id = "2983928"/>
    <advisor name = "Jenny Lee Lindberg"/>
    <academic-standing  gpa = "3.8"
                        major = "Political Science"
                        minor = "Law"
    />
    <metriculation-status status = "full-time"
                          year = "third year"
                          start-date = "08-25-1998"
                          graduation-date = "05-01-2002"
    />
  </student>

  <student>
    <personal-info>
      <identifiers  first = "Mike"
                    last = "Inez"
      />
      <contact  email = "mike@aic.com"
                phone = "213.444.3323"

      />
    </personal-info>
    <student-id id = "7645726"/>
    <advisor name = "Jerry Cantrell"/>
    <academic-standing  gpa = "4.0"
                        major = "Business Management"
                        minor = "Math"
    />
    <metriculation-status status = "full-time"
                          year = "second year"
                          start-date = "08-25-1984"
                          graduation-date = "05-01-1988"
    />
  </student>
</student-body>
